# Generated by Django 3.2.13 on 2022-11-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOne',
            fields=[
                ('CP_id', models.IntegerField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=30)),
                ('P_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SectionTwo',
            fields=[
                ('D_id', models.IntegerField(primary_key=True, serialize=False)),
                ('D_name', models.CharField(max_length=30)),
                ('CP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sectionone')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyGenerators',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('device_capacity', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('D_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sectiontwo')),
            ],
        ),
    ]
