# Generated by Django 3.2.13 on 2022-11-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='section_one',
            fields=[
                ('cp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='section_two',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30)),
                ('cp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section_one')),
            ],
        ),
        migrations.CreateModel(
            name='emergency_generators',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=30)),
                ('period_starttime', models.DateField()),
                ('period_endttime', models.DateField()),
                ('device_capacity', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('january', models.FloatField()),
                ('february', models.FloatField()),
                ('march', models.FloatField()),
                ('april', models.FloatField()),
                ('may', models.FloatField()),
                ('june', models.FloatField()),
                ('july', models.FloatField()),
                ('august', models.FloatField()),
                ('september', models.FloatField()),
                ('october', models.FloatField()),
                ('november', models.FloatField()),
                ('december', models.FloatField()),
                ('image_note', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=100)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section_two')),
            ],
        ),
    ]
