# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class section_one(models.Model):
    cpid = models.AutoField(primary_key=True)
    c_name = models.IntegerField()
    p_name = models.CharField(max_length=30)
class section_two(models.Model):
    did = models.AutoField(primary_key=True)
    d_name = models.CharField(max_length=30)
    cpid = models.ForeignKey(section_one, on_delete=models.CASCADE)
    t_name = models.CharField(max_length=30)

class emergency_generators(models.Model):
    id = models.AutoField(primary_key=True,)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=1)
    device_id = models.CharField(max_length=30)
    period_starttime = models.DateField()
    period_endtime = models.DateField()
    device_capacity = models.IntegerField()
    position = models.CharField(max_length=30)
    department = models.CharField(max_length=100)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    image_note = models.CharField(max_length=30)
    # image_path = models.ImageField(upload_to='img/')

class combustion_equipment(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=2)
    device_name = models.CharField(max_length=50)
    device_id = models.CharField(max_length=30)
    fuel_type = models.CharField(max_length=10)
    period_starttime = models.DateField()
    period_endtime = models.DateField()
    fuel_january = models.FloatField()
    fuel_february = models.FloatField()
    fuel_march = models.FloatField()
    fuel_april = models.FloatField()
    fuel_may = models.FloatField()
    fuel_june = models.FloatField()
    fuel_july = models.FloatField()
    fuel_august = models.FloatField()
    fuel_september = models.FloatField()
    fuel_october = models.FloatField()
    fuel_november = models.FloatField()
    fuel_december = models.FloatField()
    heat_january = models.FloatField()
    heat_february = models.FloatField()
    heat_march = models.FloatField()
    heat_april = models.FloatField()
    heat_may = models.FloatField()
    heat_june = models.FloatField()
    heat_july = models.FloatField()
    heat_august = models.FloatField()
    heat_september = models.FloatField()
    heat_october = models.FloatField()
    heat_november = models.FloatField()
    heat_december = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class official_car(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=3)
    vehicle_type = models.CharField(max_length=10)
    device_id = models.CharField(max_length=30)
    fuel_type = models.CharField(max_length=30)
    department = models.CharField(max_length=100)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class material(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=4)
    material_name = models.CharField(max_length=20)
    material_id = models.CharField(max_length=30)
    material_type = models.CharField(max_length=10)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()

class process(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=5)
    process_add_name = models.CharField(max_length=20)
    chemical_name = models.CharField(max_length=20)
    chemical_formula = models.CharField(max_length=20)
    process_stage = models.CharField(max_length=20)
    material_id = models.CharField(max_length=30)
    CAS_NO = models.CharField(max_length=20)
    burn = models.BooleanField()
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class refrigerator(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class airconditioner(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=7)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class vehicle(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=8)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class water_dispenser(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=9)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class ice_water_dispenser(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=10)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class ice_maker(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=11)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class other_device(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=12)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class refrigerant_total_table(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=13)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField()
    filling_date = models.DateField()
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class extinguisher(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=14)
    extinguisher_name = models.CharField(max_length=50)
    extinguisher_type = models.CharField(max_length=50)
    device_id = models.CharField(max_length=30)
    position = models.CharField(max_length=100)
    extinguisher_vendor = models.CharField(max_length=30)
    inventory = models.IntegerField()
    chemical_spec = models.IntegerField()
    chemical_weight = models.IntegerField()
    using_amount = models.IntegerField()
    using_date = models.DateField()
    replace_filling_amount = models.IntegerField()
    replace_filling_date = models.DateField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class personnel_inventory(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=15)
    years = models.IntegerField()
    monthly = models.IntegerField()
    employee_number = models.IntegerField()
    daily_hours = models.IntegerField()
    working_days = models.IntegerField()
    overtime = models.FloatField()
    leave_hours = models.IntegerField()
    day_off_hours = models.IntegerField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class security(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=16)
    years = models.IntegerField()
    monthly = models.IntegerField()
    security_number = models.IntegerField()
    daily_hours = models.IntegerField()
    working_days = models.IntegerField()
    total_working_hours = models.IntegerField()
    total_working_day = models.IntegerField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class electricity(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=17)
    EMI_id = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class upstream_transportation(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=18)
    acceptance_receipt = models.CharField(max_length=50)
    commodity_name = models.CharField(max_length=20)
    commodity_NW = models.FloatField()
    customer = models.CharField(max_length=50)
    supplier = models.CharField(max_length=30)
    supplier_address = models.CharField(max_length=100)
    trade_term = models.CharField(max_length=10)
    receiving_address = models.CharField(max_length=100)
    delivery_address = models.CharField(max_length=100)
    transport_distance = models.FloatField()
    transport_country = models.CharField(max_length=20)
    transport_type = models.CharField(max_length=20)
    vehicle_fuel = models.CharField(max_length=20)
    trips = models.IntegerField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)
    overseas_transport_distance = models.FloatField()
    overseas_transport_country = models.CharField(max_length=20)
    overseas_transport_type = models.CharField(max_length=20)
    overseas_vehicle_fuel = models.CharField(max_length=20)
    overseas_trips = models.IntegerField()
    overseas_image_note = models.CharField(max_length=30)
    overseas_image_path = models.CharField(max_length=100)
    special_transport_distance = models.FloatField()
    special_transport_country = models.CharField(max_length=20)
    special_transport_type = models.CharField(max_length=20)
    special_vehicle_fuel = models.CharField(max_length=20)
    special_trips = models.IntegerField()
    special_image_note = models.CharField(max_length=30)
    special_image_path = models.CharField(max_length=100)

class downstream_transportation(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=19)
    acceptance_receipt = models.CharField(max_length=50)
    commodity_name = models.CharField(max_length=20)
    commodity_NW = models.FloatField()
    customer = models.CharField(max_length=50)
    supplier = models.CharField(max_length=30)
    supplier_address = models.CharField(max_length=100)
    trade_term = models.CharField(max_length=10)
    receiving_address = models.CharField(max_length=100)
    delivery_address = models.CharField(max_length=100)
    transport_distance = models.FloatField()
    transport_country = models.CharField(max_length=20)
    transport_type = models.CharField(max_length=20)
    vehicle_fuel = models.CharField(max_length=20)
    trips = models.IntegerField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)
    overseas_transport_distance = models.FloatField()
    overseas_transport_country = models.CharField(max_length=20)
    overseas_transport_type = models.CharField(max_length=20)
    overseas_vehicle_fuel = models.CharField(max_length=20)
    overseas_trips = models.IntegerField()
    overseas_image_note = models.CharField(max_length=30)
    overseas_image_path = models.CharField(max_length=100)
    special_transport_distance = models.FloatField()
    special_transport_country = models.CharField(max_length=20)
    special_transport_type = models.CharField(max_length=20)
    special_vehicle_fuel = models.CharField(max_length=20)
    special_trips = models.IntegerField()
    special_image_note = models.CharField(max_length=30)
    special_image_path = models.CharField(max_length=100)

class employee_commute(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=20)
    employee_id = models.CharField(max_length=30)
    employee_name = models.CharField(max_length=10)
    department = models.CharField(max_length=100)
    work_days = models.IntegerField()
    transportation = models.CharField(max_length=20)
    displacement = models.IntegerField()
    city = models.CharField(max_length=100)
    township = models.CharField(max_length=10)
    address = models.CharField(max_length=100)
    commute_distance = models.FloatField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)

class employee_business_trip(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=21)
    business_trip_location = models.CharField(max_length=100)
    business_trip_date = models.DateField()
    transportation = models.CharField(max_length=20)
    employee_id = models.CharField(max_length=30)
    employee_name = models.CharField(max_length=10)
    department = models.CharField(max_length=100)
    departure = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    bt_image_note = models.CharField(max_length=30)
    bt_image_path = models.CharField(max_length=100)
    round_trip_distance = models.IntegerField()
    rtd_image_note = models.CharField(max_length=30)
    rtd_image_path = models.CharField(max_length=100)

class waste(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=22)
    waste_name = models.CharField(max_length=50)
    waste_weigh = models.IntegerField()
    waste_date = models.DateField()
    waste_disposal = models.CharField(max_length=20)
    waste_location = models.CharField(max_length=100)
    transport_responsibility = models.CharField(max_length=20)
    transport_type = models.CharField(max_length=20)
    transport_fuel = models.CharField(max_length=10)
    transport_distance = models.IntegerField()
    image_note = models.CharField(max_length=30)
    image_path = models.CharField(max_length=100)
