# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User
import datetime

# 限制文件
from django.core import validators

YEAR_CHOICES = []
for r in range(1980, (datetime.datetime.now().year + 1)):
    YEAR_CHOICES.append((r, r))


# Create your models here.
class section_one(models.Model):
    cpid = models.AutoField(primary_key=True)
    c_name = models.IntegerField()
    p_name = models.CharField(max_length=30)


class section_two(models.Model):
    did = models.AutoField(primary_key=True)
    d_name = models.CharField(max_length=30)
    cpid = models.ForeignKey(section_one, on_delete=models.CASCADE)
    t_name = models.CharField(max_length=30)


class emergency_generators(models.Model):
    id = models.AutoField(primary_key=True, )
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=1)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_capacity = models.IntegerField()
    position = models.CharField(max_length=30)
    department = models.CharField(max_length=100, null=True)
    january = models.FloatField(default=0)
    february = models.FloatField(default=0)
    march = models.FloatField(default=0)
    april = models.FloatField(default=0)
    may = models.FloatField(default=0)
    june = models.FloatField(default=0)
    july = models.FloatField(default=0)
    august = models.FloatField(default=0)
    september = models.FloatField(default=0)
    october = models.FloatField(default=0)
    november = models.FloatField(default=0)
    december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='緊急發電機/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class combustion_equipment(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=2)
    years = models.IntegerField()
    device_name = models.CharField(max_length=50)
    device_id = models.CharField(max_length=30)
    fuel_type = models.CharField(max_length=10)
    fuel_january = models.FloatField(default=0)
    fuel_february = models.FloatField(default=0)
    fuel_march = models.FloatField(default=0)
    fuel_april = models.FloatField(default=0)
    fuel_may = models.FloatField(default=0)
    fuel_june = models.FloatField(default=0)
    fuel_july = models.FloatField(default=0)
    fuel_august = models.FloatField(default=0)
    fuel_september = models.FloatField(default=0)
    fuel_october = models.FloatField(default=0)
    fuel_november = models.FloatField(default=0)
    fuel_december = models.FloatField(default=0)
    heat_january = models.FloatField(default=0)
    heat_february = models.FloatField(default=0)
    heat_march = models.FloatField(default=0)
    heat_april = models.FloatField(default=0)
    heat_may = models.FloatField(default=0)
    heat_june = models.FloatField(default=0)
    heat_july = models.FloatField(default=0)
    heat_august = models.FloatField(default=0)
    heat_september = models.FloatField(default=0)
    heat_october = models.FloatField(default=0)
    heat_november = models.FloatField(default=0)
    heat_december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='燃燒設備/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class official_car(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=3)
    years = models.IntegerField()
    vehicle_type = models.CharField(max_length=10)
    device_id = models.CharField(max_length=30)
    fuel_type = models.CharField(max_length=30)
    department = models.CharField(max_length=100, null=True)
    metering_method = models.CharField(max_length=20)
    oil_january = models.FloatField(default=0)
    oil_february = models.FloatField(default=0)
    oil_march = models.FloatField(default=0)
    oil_april = models.FloatField(default=0)
    oil_may = models.FloatField(default=0)
    oil_june = models.FloatField(default=0)
    oil_july = models.FloatField(default=0)
    oil_august = models.FloatField(default=0)
    oil_september = models.FloatField(default=0)
    oil_october = models.FloatField(default=0)
    oil_november = models.FloatField(default=0)
    oil_december = models.FloatField(default=0)
    urea_january = models.FloatField(null=True)
    urea_february = models.FloatField(null=True)
    urea_march = models.FloatField(null=True)
    urea_april = models.FloatField(null=True)
    urea_may = models.FloatField(null=True)
    urea_june = models.FloatField(null=True)
    urea_july = models.FloatField(null=True)
    urea_august = models.FloatField(null=True)
    urea_september = models.FloatField(null=True)
    urea_october = models.FloatField(null=True)
    urea_november = models.FloatField(null=True)
    urea_december = models.FloatField(null=True)
    elec_january = models.FloatField(default=0)
    elec_february = models.FloatField(default=0)
    elec_march = models.FloatField(default=0)
    elec_april = models.FloatField(default=0)
    elec_may = models.FloatField(default=0)
    elec_june = models.FloatField(default=0)
    elec_july = models.FloatField(default=0)
    elec_august = models.FloatField(default=0)
    elec_september = models.FloatField(default=0)
    elec_october = models.FloatField(default=0)
    elec_november = models.FloatField(default=0)
    elec_december = models.FloatField(default=0)
    km_january = models.FloatField(default=0)
    km_february = models.FloatField(default=0)
    km_march = models.FloatField(default=0)
    km_april = models.FloatField(default=0)
    km_may = models.FloatField(default=0)
    km_june = models.FloatField(default=0)
    km_july = models.FloatField(default=0)
    km_august = models.FloatField(default=0)
    km_september = models.FloatField(default=0)
    km_october = models.FloatField(default=0)
    km_november = models.FloatField(default=0)
    km_december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='公務車/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class material(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=4)
    years = models.IntegerField()
    material_name = models.CharField(max_length=20)
    material_id = models.CharField(max_length=30)
    material_type = models.CharField(max_length=10)
    chemical = models.BooleanField(default=False)
    process_add_name = models.CharField(max_length=20, null=True)
    chemical_name = models.CharField(max_length=20, null=True)
    chemical_formula = models.CharField(max_length=20, null=True)
    january = models.FloatField(default=0)
    february = models.FloatField(default=0)
    march = models.FloatField(default=0)
    april = models.FloatField(default=0)
    may = models.FloatField(default=0)
    june = models.FloatField(default=0)
    july = models.FloatField(default=0)
    august = models.FloatField(default=0)
    september = models.FloatField(default=0)
    october = models.FloatField(default=0)
    november = models.FloatField(default=0)
    december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='原物料使用/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class process(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=5)
    years = models.IntegerField()
    process_add_name = models.CharField(max_length=20)
    chemical_name = models.CharField(max_length=20)
    chemical_formula = models.CharField(max_length=20, null=True)
    process_stage = models.CharField(max_length=20)
    material_id = models.CharField(max_length=30)
    CAS_NO = models.CharField(max_length=20)
    burn = models.BooleanField(default=False)
    VOCs = models.BooleanField(default=False)
    unit = models.CharField(max_length=20)
    january = models.FloatField(default=0)
    february = models.FloatField(default=0)
    march = models.FloatField(default=0)
    april = models.FloatField(default=0)
    may = models.FloatField(default=0)
    june = models.FloatField(default=0)
    july = models.FloatField(default=0)
    august = models.FloatField(default=0)
    september = models.FloatField(default=0)
    october = models.FloatField(default=0)
    november = models.FloatField(default=0)
    december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='製程添加化學品/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class refrigerator(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    position = models.CharField(max_length=100, null=True)
    filling_volume = models.FloatField(null=True)
    effusion_rate = models.FloatField()
    refrigerant_type = models.CharField(max_length=20)
    filling_fix_volume = models.FloatField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='冰箱清單/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class airconditioner(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=7)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    position = models.CharField(max_length=100, null=True)
    filling_volume = models.FloatField(null=True)
    effusion_rate = models.FloatField()
    refrigerant_type = models.CharField(max_length=20)
    filling_fix_volume = models.FloatField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='airconditioner/%Y/%m', validators=[validators.FileExtensionValidator(['jpg', 'png', 'pdf'])], null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class vehicle(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=8)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    position = models.CharField(max_length=100, null=True)
    filling_volume = models.FloatField(null=True)
    effusion_rate = models.FloatField()
    refrigerant_type = models.CharField(max_length=20)
    filling_fix_volume = models.FloatField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='車輛清單/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class water_dispenser(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=9)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    position = models.CharField(max_length=100, null=True)
    filling_volume = models.FloatField(null=True)
    effusion_rate = models.FloatField()
    refrigerant_type = models.CharField(max_length=20)
    filling_fix_volume = models.FloatField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='飲水機清單/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class ice_water_dispenser(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=10)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    position = models.CharField(max_length=100, null=True)
    filling_volume = models.FloatField(null=True)
    effusion_rate = models.FloatField()
    refrigerant_type = models.CharField(max_length=20)
    filling_fix_volume = models.FloatField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='冰水機清單/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class ice_maker(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=11)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    position = models.CharField(max_length=100, null=True)
    filling_volume = models.FloatField(null=True)
    effusion_rate = models.FloatField()
    refrigerant_type = models.CharField(max_length=20)
    filling_fix_volume = models.FloatField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='製冰機清單/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class other_device(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=12)
    years = models.IntegerField()
    device_id = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    position = models.CharField(max_length=100, null=True)
    filling_volume = models.FloatField(null=True)
    effusion_rate = models.FloatField()
    refrigerant_type = models.CharField(max_length=20)
    filling_fix_volume = models.FloatField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='其他設備清單/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class extinguisher(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=13)
    years = models.IntegerField()
    extinguisher_type = models.CharField(max_length=50)
    device_id = models.CharField(max_length=30, null=True)
    position = models.CharField(max_length=100)
    extinguisher_vendor = models.CharField(max_length=30, null=True)
    chemical_weight = models.FloatField()
    inventory = models.IntegerField()
    using_amount = models.IntegerField()
    monthly = models.CharField(max_length=20)
    replace_filling_amount = models.FloatField()
    replace_filling_date = models.CharField(max_length=20)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='滅火器/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class personnel_inventory(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=14)
    years = models.IntegerField()
    WKhours_january = models.FloatField(default=0)
    WKhours_february = models.FloatField(default=0)
    WKhours_march = models.FloatField(default=0)
    WKhours_april = models.FloatField(default=0)
    WKhours_may = models.FloatField(default=0)
    WKhours_june = models.FloatField(default=0)
    WKhours_july = models.FloatField(default=0)
    WKhours_august = models.FloatField(default=0)
    WKhours_september = models.FloatField(default=0)
    WKhours_october = models.FloatField(default=0)
    WKhours_november = models.FloatField(default=0)
    WKhours_december = models.FloatField(default=0)
    WKnum_january = models.IntegerField(default=0)
    WKnum_february = models.IntegerField(default=0)
    WKnum_march = models.IntegerField(default=0)
    WKnum_april = models.IntegerField(default=0)
    WKnum_may = models.IntegerField(default=0)
    WKnum_june = models.IntegerField(default=0)
    WKnum_july = models.IntegerField(default=0)
    WKnum_august = models.IntegerField(default=0)
    WKnum_september = models.IntegerField(default=0)
    WKnum_october = models.IntegerField(default=0)
    WKnum_november = models.IntegerField(default=0)
    WKnum_december = models.IntegerField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='人天清冊/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class employee(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=15)
    years = models.IntegerField()
    career = models.CharField(max_length=10)
    employeeNum_january = models.FloatField(default=0)
    employeeNum_february = models.FloatField(default=0)
    employeeNum_march = models.FloatField(default=0)
    employeeNum_april = models.FloatField(default=0)
    employeeNum_may = models.FloatField(default=0)
    employeeNum_june = models.FloatField(default=0)
    employeeNum_july = models.FloatField(default=0)
    employeeNum_august = models.FloatField(default=0)
    employeeNum_september = models.FloatField(default=0)
    employeeNum_october = models.FloatField(default=0)
    employeeNum_november = models.FloatField(default=0)
    employeeNum_december = models.FloatField(default=0)
    WKdays_january = models.FloatField(default=0)
    WKdays_february = models.FloatField(default=0)
    WKdays_march = models.FloatField(default=0)
    WKdays_april = models.FloatField(default=0)
    WKdays_may = models.FloatField(default=0)
    WKdays_june = models.FloatField(default=0)
    WKdays_july = models.FloatField(default=0)
    WKdays_august = models.FloatField(default=0)
    WKdays_september = models.FloatField(default=0)
    WKdays_october = models.FloatField(default=0)
    WKdays_november = models.FloatField(default=0)
    WKdays_december = models.FloatField(default=0)
    WKhours_january = models.FloatField(default=0)
    WKhours_february = models.FloatField(default=0)
    WKhours_march = models.FloatField(default=0)
    WKhours_april = models.FloatField(default=0)
    WKhours_may = models.FloatField(default=0)
    WKhours_june = models.FloatField(default=0)
    WKhours_july = models.FloatField(default=0)
    WKhours_august = models.FloatField(default=0)
    WKhours_september = models.FloatField(default=0)
    WKhours_october = models.FloatField(default=0)
    WKhours_november = models.FloatField(default=0)
    WKhours_december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='委外人員清單/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


# 廢水
class waste_water(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=16)
    years = models.IntegerField()
    waste_water_treatment_name = models.CharField(max_length=50)
    waste_water_inflow_rate = models.IntegerField()
    average_inlet_COD_concentration = models.IntegerField()
    average_COD_removal_rate = models.IntegerField()
    CH4_capture_system_rate = models.FloatField()
    combustion_equipment_efficiency = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='廢水/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


# 廢汙泥
class waste_sludge(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=17)
    years = models.IntegerField()
    waste_sludge_treatment_name = models.CharField(max_length=50)
    waste_sludge_inflow_rate = models.IntegerField()
    average_inlet_MLSS_concentration = models.IntegerField()
    CH4_capture_system_rate = models.FloatField()
    combustion_equipment_efficiency = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='廢汙泥/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


# 溶劑、噴霧劑
class solvent_aerosol_emission_sources(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=18)
    years = models.IntegerField()
    solvent_name = models.CharField(max_length=100)
    solvent_amount = models.FloatField()
    solvent_amount_unit = models.CharField(max_length=30)
    solvent_capacity = models.FloatField()
    solvent_capacity_unit = models.CharField(max_length=30)
    fugitive_recharge = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='用電量/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class additive_section(models.Model):
    id = models.AutoField(primary_key=True)
    additive_name = models.CharField(max_length=100)
    additive_amount = models.FloatField()
    additive_unit = models.CharField(max_length=30)
    additive_ingredient = models.CharField(max_length=255)
    additive_ratio = models.CharField(max_length=30)
    additive_id = models.ForeignKey(solvent_aerosol_emission_sources, on_delete=models.CASCADE)


class electricity(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=21)
    years = models.IntegerField()
    EMI_id = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    january = models.FloatField(default=0)
    february = models.FloatField(default=0)
    march = models.FloatField(default=0)
    april = models.FloatField(default=0)
    may = models.FloatField(default=0)
    june = models.FloatField(default=0)
    july = models.FloatField(default=0)
    august = models.FloatField(default=0)
    september = models.FloatField(default=0)
    october = models.FloatField(default=0)
    november = models.FloatField(default=0)
    december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='用電量/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class upstream_transportation(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=22)
    acceptance_receipt = models.CharField(max_length=50)
    commodity_name = models.CharField(max_length=20)
    weight = models.CharField(max_length=10)
    commodity_NW = models.FloatField()
    organizational_use_products = models.CharField(max_length=100)
    customer = models.CharField(max_length=50)
    supplier = models.CharField(max_length=30)
    supplier_address = models.CharField(max_length=100)
    trade_term = models.CharField(max_length=10)
    receiving_address = models.CharField(max_length=100)
    delivery_address = models.CharField(max_length=100)
    transport_distance = models.FloatField(null=True)
    transport_country = models.CharField(max_length=20, null=True)
    paid = models.CharField(max_length=10)
    transport_type = models.CharField(max_length=20, null=True)
    transport_fuel = models.CharField(max_length=20, null=True)
    trips = models.IntegerField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='上游運輸/%Y/%m', null=True, default=None)
    overseas_transport_distance = models.FloatField(null=True)
    overseas_paid = models.CharField(max_length=10, null=True)
    overseas_delivery = models.CharField(max_length=50, null=True)
    overseas_arrive = models.CharField(max_length=50, null=True)
    overseas_trips = models.IntegerField(null=True)
    overseas_image_note = models.CharField(max_length=30, null=True)
    overseas_image_path = models.FileField(upload_to='上游運輸/%Y/%m', null=True, default=None)
    special_transport_distance = models.FloatField(null=True)
    special_transport_country = models.CharField(max_length=20, null=True)
    special_paid = models.CharField(max_length=10, null=True)
    special_transport_type = models.CharField(max_length=20, null=True)
    special_transport_fuel = models.CharField(max_length=20, null=True)
    special_trips = models.IntegerField(null=True)
    special_image_note = models.CharField(max_length=30, null=True)
    special_image_path = models.FileField(upload_to='上游運輸/%Y/%m', null=True, default=None)
    air_transport_distance = models.FloatField(null=True)
    air_delivery = models.CharField(max_length=50, null=True)
    air_arrive = models.CharField(max_length=50, null=True)
    air_trips = models.IntegerField(null=True)
    air_paid = models.CharField(max_length=10, null=True)
    air_image_note = models.CharField(max_length=30, null=True)
    air_image_path = models.FileField(upload_to='上游運輸/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class downstream_transportation(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=23)
    acceptance_receipt = models.CharField(max_length=50)
    commodity_name = models.CharField(max_length=20)
    weight = models.CharField(max_length=10)
    commodity_NW = models.FloatField()
    customer = models.CharField(max_length=50)
    supplier = models.CharField(max_length=30)
    supplier_address = models.CharField(max_length=100)
    trade_term = models.CharField(max_length=10)
    receiving_address = models.CharField(max_length=100)
    delivery_address = models.CharField(max_length=100)
    transport_distance = models.FloatField(null=True)
    transport_country = models.CharField(max_length=20, null=True)
    paid = models.CharField(max_length=10)
    transport_type = models.CharField(max_length=20, null=True)
    transport_fuel = models.CharField(max_length=20, null=True)
    trips = models.IntegerField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='下游運輸/%Y/%m', null=True, default=None)
    overseas_transport_distance = models.FloatField(null=True)
    overseas_paid = models.CharField(max_length=10)
    overseas_delivery = models.CharField(max_length=50, null=True)
    overseas_arrive = models.CharField(max_length=50, null=True)
    overseas_trips = models.IntegerField(null=True)
    overseas_image_note = models.CharField(max_length=30, null=True)
    overseas_image_path = models.FileField(upload_to='下游運輸/%Y/%m', null=True, default=None)
    special_transport_distance = models.FloatField(null=True)
    special_transport_country = models.CharField(max_length=20, null=True)
    special_paid = models.CharField(max_length=10)
    special_transport_type = models.CharField(max_length=20, null=True)
    special_transport_fuel = models.CharField(max_length=20, null=True)
    special_trips = models.IntegerField(null=True)
    special_image_note = models.CharField(max_length=30, null=True)
    special_image_path = models.FileField(upload_to='下游運輸/%Y/%m', null=True, default=None)
    air_transport_distance = models.FloatField(null=True)
    air_delivery = models.CharField(max_length=50, null=True)
    air_arrive = models.CharField(max_length=50, null=True)
    air_trips = models.IntegerField(null=True)
    air_paid = models.CharField(max_length=10)
    air_image_note = models.CharField(max_length=30, null=True)
    air_image_path = models.FileField(upload_to='下游運輸/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class employee_commute(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=24)
    years = models.IntegerField()
    employee_id = models.CharField(max_length=30)
    employee_name = models.CharField(max_length=10)
    department = models.CharField(max_length=100)
    work_days = models.IntegerField()
    city = models.CharField(max_length=100)
    township = models.CharField(max_length=10)
    address = models.CharField(max_length=100)
    commute_distance = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='員工通勤/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class transportation_way(models.Model):
    id = models.AutoField(primary_key=True)
    transportation = models.CharField(max_length=30)
    commute = models.ForeignKey(employee_commute, on_delete=models.CASCADE)


class employee_business_trip(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=25)
    business_trip_location = models.CharField(max_length=100)
    business_trip_date = models.CharField(max_length=30)
    business_trip_number = models.CharField(max_length=30)
    employee_id = models.CharField(max_length=30, null=True)
    employee_name = models.CharField(max_length=10)
    department = models.CharField(max_length=100)
    bt_image_note = models.CharField(max_length=30, null=True)
    bt_image_path = models.FileField(upload_to='員工出差/%Y/%m', null=True, default=None)
    rtd_image_note = models.CharField(max_length=30, null=True)
    rtd_image_path = models.FileField(upload_to='員工出差/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class trip_section(models.Model):
    id = models.AutoField(primary_key=True)
    departure = models.CharField(max_length=50)
    transportation = models.CharField(max_length=30)
    distance = models.FloatField()
    trip_id = models.ForeignKey(employee_business_trip, on_delete=models.CASCADE)


class VOCs_one(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=22)
    years = models.IntegerField()
    emission = models.FloatField()
    concentration_ch4 = models.FloatField()
    message_board = models.CharField(max_length=255, null=True)


class VOCs_two(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=23)
    years = models.IntegerField()
    disposal_volume = models.FloatField()
    concentration_entrance = models.FloatField(null=True)
    concentration_exit = models.FloatField(null=True)
    builtIn_rate = models.FloatField(null=True)
    custom_rate = models.FloatField(null=True)
    concentration_ch4 = models.FloatField()
    voc_capture_rate = models.FloatField()
    combustion_equipment_rate = models.FloatField()
    radio_VOCs = models.CharField(max_length=20)
    radio_concentration = models.CharField(max_length=20, null=True)
    radio_co2_emission = models.CharField(max_length=20, null=True)
    message_board = models.CharField(max_length=255, null=True)


class waste(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=26)
    waste_name = models.CharField(max_length=50)
    waste_weigh = models.IntegerField()
    waste_date = models.CharField(max_length=20)
    waste_disposal = models.CharField(max_length=20)
    waste_location = models.CharField(max_length=100)
    waste_disposal_vendor = models.CharField(max_length=20)
    transport_type = models.CharField(max_length=50, null=True)
    transport_fuel = models.CharField(max_length=10, null=True)
    transport_distance = models.IntegerField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.FileField(upload_to='廢棄物/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class chemical_table(models.Model):
    chemical_add = models.CharField(primary_key=True, max_length=50)
    chemical_name = models.CharField(max_length=50)
    chemical_formula = models.CharField(max_length=50)


class image(models.Model):
    id = models.AutoField(primary_key=True)
    ac = models.ForeignKey(airconditioner, on_delete=models.CASCADE)
    image_path = models.FileField(upload_to='airconditioner/%Y/%m', validators=[validators.FileExtensionValidator(['jpg', 'png', 'pdf'])], null=True, default=None)
