# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User
import datetime

YEAR_CHOICES = []
for r in range(1980, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r, r))

# Create your models here.
class section_one(models.Model):
    cpid = models.AutoField(primary_key=True)
    c_name = models.IntegerField()
    p_name = models.CharField(max_length=30)
class section_two(models.Model):
    did = models.AutoField(primary_key=True)
    d_name = models.CharField(max_length=30)
    cpid = models.ForeignKey(section_one, on_delete=models.CASCADE)
    t_name = models.CharField(max_length=30)

class emergency_generators(models.Model):
    id = models.AutoField(primary_key=True,)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=1)
    device_id = models.CharField(max_length=30)
    years = models.IntegerField()
    device_capacity = models.IntegerField()
    position = models.CharField(max_length=30)
    department = models.CharField(max_length=100, null=True)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='emergency_generators/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class combustion_equipment(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=2)
    device_name = models.CharField(max_length=50)
    device_id = models.CharField(max_length=30)
    fuel_type = models.CharField(max_length=10)
    years = models.IntegerField()
    fuel_january = models.FloatField()
    fuel_february = models.FloatField()
    fuel_march = models.FloatField()
    fuel_april = models.FloatField()
    fuel_may = models.FloatField()
    fuel_june = models.FloatField()
    fuel_july = models.FloatField()
    fuel_august = models.FloatField()
    fuel_september = models.FloatField()
    fuel_october = models.FloatField()
    fuel_november = models.FloatField()
    fuel_december = models.FloatField()
    heat_january = models.FloatField(default=0)
    heat_february = models.FloatField(default=0)
    heat_march = models.FloatField(default=0)
    heat_april = models.FloatField(default=0)
    heat_may = models.FloatField(default=0)
    heat_june = models.FloatField(default=0)
    heat_july = models.FloatField(default=0)
    heat_august = models.FloatField(default=0)
    heat_september = models.FloatField(default=0)
    heat_october = models.FloatField(default=0)
    heat_november = models.FloatField(default=0)
    heat_december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='combustion_equipment/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class official_car(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=3)
    vehicle_type = models.CharField(max_length=10)
    years = models.IntegerField()
    fuel_type = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    department = models.CharField(max_length=100, null=True)
    metering_method = models.CharField(max_length=20)
    oil_january = models.FloatField(default=0)
    oil_february = models.FloatField(default=0)
    oil_march = models.FloatField(default=0)
    oil_april = models.FloatField(default=0)
    oil_may = models.FloatField(default=0)
    oil_june = models.FloatField(default=0)
    oil_july = models.FloatField(default=0)
    oil_august = models.FloatField(default=0)
    oil_september = models.FloatField(default=0)
    oil_october = models.FloatField(default=0)
    oil_november = models.FloatField(default=0)
    oil_december = models.FloatField(default=0)
    urea_january = models.FloatField(default=0)
    urea_february = models.FloatField(default=0)
    urea_march = models.FloatField(default=0)
    urea_april = models.FloatField(default=0)
    urea_may = models.FloatField(default=0)
    urea_june = models.FloatField(default=0)
    urea_july = models.FloatField(default=0)
    urea_august = models.FloatField(default=0)
    urea_september = models.FloatField(default=0)
    urea_october = models.FloatField(default=0)
    urea_november = models.FloatField(default=0)
    urea_december = models.FloatField(default=0)
    elec_january = models.FloatField(default=0)
    elec_february = models.FloatField(default=0)
    elec_march = models.FloatField(default=0)
    elec_april = models.FloatField(default=0)
    elec_may = models.FloatField(default=0)
    elec_june = models.FloatField(default=0)
    elec_july = models.FloatField(default=0)
    elec_august = models.FloatField(default=0)
    elec_september = models.FloatField(default=0)
    elec_october = models.FloatField(default=0)
    elec_november = models.FloatField(default=0)
    elec_december = models.FloatField(default=0)
    km_january = models.FloatField(default=0)
    km_february = models.FloatField(default=0)
    km_march = models.FloatField(default=0)
    km_april = models.FloatField(default=0)
    km_may = models.FloatField(default=0)
    km_june = models.FloatField(default=0)
    km_july = models.FloatField(default=0)
    km_august = models.FloatField(default=0)
    km_september = models.FloatField(default=0)
    km_october = models.FloatField(default=0)
    km_november = models.FloatField(default=0)
    km_december = models.FloatField(default=0)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='official_car/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)


class material(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=4)
    material_name = models.CharField(max_length=20)
    material_id = models.CharField(max_length=30)
    material_type = models.CharField(max_length=10)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    message_board = models.CharField(max_length=255, null=True)

class process(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=5)
    process_add_name = models.CharField(max_length=20)
    chemical_name = models.CharField(max_length=20)
    chemical_formula = models.CharField(max_length=20, null=True)
    process_stage = models.CharField(max_length=20)
    material_id = models.CharField(max_length=30)
    CAS_NO = models.CharField(max_length=20)
    burn = models.BooleanField(default=False)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='process/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class refrigerator(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='refrigerator/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class airconditioner(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='airconditioner/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class vehicle(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='vehicle/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class water_dispenser(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='water_dispenser/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class ice_water_dispenser(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='ice_water_dispenser/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class ice_maker(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='ice_maker/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class other_device(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='other_device/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class refrigerant_total_table(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=6)
    device_name = models.CharField(max_length=30)
    device_id = models.CharField(max_length=30)
    brand_name = models.CharField(max_length=30, null=True)
    model_type = models.CharField(max_length=50)
    years = models.IntegerField()
    position = models.CharField(max_length=100, null=True)
    refrigerant_type = models.CharField(max_length=20)
    filling_volume = models.FloatField()
    filling_fix_volume = models.FloatField(null=True)
    filling_date = models.DateField(null=True)
    effusion_rate = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='refrigerant_total_table/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class extinguisher(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=14)
    extinguisher_name = models.CharField(max_length=50)
    extinguisher_type = models.CharField(max_length=50)
    device_id = models.CharField(max_length=30)
    position = models.CharField(max_length=100)
    extinguisher_vendor = models.CharField(max_length=30, null=True)
    inventory = models.IntegerField()
    chemical_spec = models.IntegerField()
    chemical_weight = models.IntegerField()
    using_amount = models.IntegerField()
    using_date = models.DateField()
    replace_filling_amount = models.IntegerField()
    replace_filling_date = models.DateField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='extinguisher/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class personnel_inventory(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=15)
    years = models.IntegerField()
    monthly = models.IntegerField()
    employee_number = models.IntegerField()
    daily_hours = models.IntegerField(null=True)
    working_days = models.IntegerField(null=True)
    overtime = models.FloatField(null=True)
    leave_hours = models.IntegerField(null=True)
    day_off_hours = models.IntegerField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='personnel_inventory/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class security(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=16)
    years = models.IntegerField()
    monthly = models.IntegerField()
    security_number = models.IntegerField()
    daily_hours = models.IntegerField()
    working_days = models.IntegerField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='security/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class electricity(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=17)
    EMI_id = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    january = models.FloatField()
    february = models.FloatField()
    march = models.FloatField()
    april = models.FloatField()
    may = models.FloatField()
    june = models.FloatField()
    july = models.FloatField()
    august = models.FloatField()
    september = models.FloatField()
    october = models.FloatField()
    november = models.FloatField()
    december = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='electricity/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class upstream_transportation(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=18)
    acceptance_receipt = models.CharField(max_length=50)
    commodity_name = models.CharField(max_length=20)
    commodity_NW = models.FloatField()
    customer = models.CharField(max_length=50)
    supplier = models.CharField(max_length=30)
    supplier_address = models.CharField(max_length=100)
    trade_term = models.CharField(max_length=10)
    receiving_address = models.CharField(max_length=100)
    delivery_address = models.CharField(max_length=100)
    transport_distance = models.FloatField(null=True)
    transport_country = models.CharField(max_length=20, null=True)
    transport_type = models.CharField(max_length=20, null=True)
    vehicle_fuel = models.CharField(max_length=20, null=True)
    trips = models.IntegerField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='upstream_transportation/%Y/%m', null=True, default=None)
    overseas_transport_distance = models.FloatField(null=True)
    overseas_transport_type = models.CharField(max_length=20, null=True)
    overseas_delivery = models.CharField(max_length=50, null=True)
    overseas_arrive = models.CharField(max_length=50, null=True)
    overseas_trips = models.IntegerField(null=True)
    overseas_image_note = models.CharField(max_length=30, null=True)
    overseas_image_path = models.ImageField(upload_to='upstream_transportation/%Y/%m', null=True, default=None)
    special_transport_distance = models.FloatField(null=True)
    special_transport_country = models.CharField(max_length=20, null=True)
    special_transport_type = models.CharField(max_length=20, null=True)
    special_vehicle_fuel = models.CharField(max_length=20, null=True)
    special_trips = models.IntegerField(null=True)
    special_image_note = models.CharField(max_length=30, null=True)
    special_image_path = models.ImageField(upload_to='upstream_transportation/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class downstream_transportation(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=19)
    acceptance_receipt = models.CharField(max_length=50)
    commodity_name = models.CharField(max_length=20)
    commodity_NW = models.FloatField()
    customer = models.CharField(max_length=50)
    supplier = models.CharField(max_length=30)
    supplier_address = models.CharField(max_length=100)
    trade_term = models.CharField(max_length=10)
    receiving_address = models.CharField(max_length=100)
    delivery_address = models.CharField(max_length=100)
    transport_distance = models.FloatField(null=True)
    transport_country = models.CharField(max_length=20, null=True)
    transport_type = models.CharField(max_length=20, null=True)
    vehicle_fuel = models.CharField(max_length=20, null=True)
    trips = models.IntegerField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='downstream_transportation/%Y/%m', null=True, default=None)
    overseas_transport_distance = models.FloatField(null=True)
    overseas_transport_type = models.CharField(max_length=20, null=True)
    overseas_delivery = models.CharField(max_length=50, null=True)
    overseas_arrive = models.CharField(max_length=50, null=True)
    overseas_trips = models.IntegerField(null=True)
    overseas_image_note = models.CharField(max_length=30, null=True)
    overseas_image_path = models.ImageField(upload_to='downstream_transportation/%Y/%m', null=True, default=None)
    special_transport_distance = models.FloatField(null=True)
    special_transport_country = models.CharField(max_length=20, null=True)
    special_transport_type = models.CharField(max_length=20, null=True)
    special_vehicle_fuel = models.CharField(max_length=20, null=True)
    special_trips = models.IntegerField(null=True)
    special_image_note = models.CharField(max_length=30, null=True)
    special_image_path = models.ImageField(upload_to='downstream_transportation/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class employee_commute(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=20)
    employee_id = models.CharField(max_length=30)
    employee_name = models.CharField(max_length=10)
    department = models.CharField(max_length=100)
    work_days = models.IntegerField()
    transportation = models.CharField(max_length=20)
    displacement = models.IntegerField()
    city = models.CharField(max_length=100)
    township = models.CharField(max_length=10)
    address = models.CharField(max_length=100)
    commute_distance = models.FloatField()
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='employee_commute/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class employee_business_trip(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=21)
    business_trip_location = models.CharField(max_length=100)
    business_trip_date = models.DateField()
    transportation = models.CharField(max_length=20)
    employee_id = models.CharField(max_length=30)
    employee_name = models.CharField(max_length=10)
    department = models.CharField(max_length=100)
    departure = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    bt_image_note = models.CharField(max_length=30, null=True)
    bt_image_path = models.ImageField(upload_to='employee_business_trip/%Y/%m', null=True, default=None)
    round_trip_distance = models.IntegerField()
    rtd_image_note = models.CharField(max_length=30, null=True)
    rtd_image_path = models.ImageField(upload_to='employee_business_trip/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)

class waste(models.Model):
    id = models.AutoField(primary_key=True)
    did = models.ForeignKey(section_two, on_delete=models.CASCADE, default=22)
    waste_name = models.CharField(max_length=50)
    waste_weigh = models.IntegerField()
    waste_date = models.DateField()
    waste_disposal = models.CharField(max_length=20)
    waste_location = models.CharField(max_length=100)
    waste_disposal_vendor = models.CharField(max_length=20)
    transport_type = models.CharField(max_length=20, null=True)
    transport_fuel = models.CharField(max_length=10, null=True)
    transport_distance = models.IntegerField(null=True)
    image_note = models.CharField(max_length=30, null=True)
    image_path = models.ImageField(upload_to='waste/%Y/%m', null=True, default=None)
    message_board = models.CharField(max_length=255, null=True)
